### ISSUE TITLE
PhpStorm (10.0.1): CodeGlance 1.4.4 plugin "disappears" from installed plugins after restart

### ISSUE THREAD

**Issue by jisuo** [Vektah/CodeGlance#106]
- I open settings in PhpStorm, select Plugins
- Browse repositories, search for CodeGlance
- Click install
- It asks to restart PhpStorm, I click ok
- Plugin gone from installed Plugins list after restart

Not sure if this is CodeGlance or PhpStorm issue?

**Comment by Vektah** [comment]
If you download http://public.vektah.net/codeglance/net/vektah/CodeGlance/1.4.4/CodeGlance-1.4.4.zip manually and "Install plugin from disk..."

Does that work?

**Comment by lahmann** [comment]
Same applies to PhpStorm 9.0.2. Even worse is, after manually installing CodeGlance 1.4.3 the plugin is enabled in Plugins-Settings but does not show up in Editor-Window.

**Comment by jisuo** [comment]
@Vektah 

Hey,
Yes that did work. It also works on all files with this new version. Thanks!

**Comment by jisuo** [comment]
@lahmann Update to 1.4.4

**Comment by lahmann** [comment]
http://public.vektah.net/codeglance/net/vektah/CodeGlance/1.4.4/CodeGlance-1.4.4.zip
Does not work for me either - if I rename the zip to jar in order to let PhpStorm recognize the file, PhpStorm tells me "Fail to load plugin descriptor from file CodeGlance-1.4.4.jar", unzipping the archive does not help either.

@jisuo that's what I did - and CodeGlance disappeared from the plugins list as it did for you. Manual install does not work either.

**Comment by Vektah** [comment]
@lahmann You can take the thermonuclear option:
 - Close phpstorm
 - Go to C:\Users\<User>\.IntelliJIdea15\config\plugins
 - delete all the CodeGlance things from here
 - download a fresh copy from the link above (it should be .zip)
 - reinstall

**Comment by lahmann** [comment]
Ok, problem solved - after unzipping above provided zip-file manually into .WebIde90/config/plugins (and removing any CodeGlance files) and restarting PhpStorm CodeGlance works again.
Thanks for the quick help.

**Comment by Vektah** [comment]
Apologies for the botched release, lets hope there are no other issues :)
