### ISSUE TITLE
Plugin leaks memory

### ISSUE THREAD

**Issue by nicity** [Vektah/CodeGlance#99]
There are strong references to CodeGlancePanel from CodeGlancePlugin.injector.panels
In memory snapshot attached to https://youtrack.jetbrains.com/issue/IDEA-148182 there are 134 such panels with retained size 300M

**Comment by talanb** [comment]
I was the one that submitted this issue to Jetbrains and I now have some additional information. I have my IDE configured with the tab placement set to None and a tab limit of 1 so that I only have one editor available. However, as I navigate through my project with this configuration, fileClosed is never called so the GlancePanel is never getting uninject-ed and is leaking memory. I'm not sure how to be notified of these navigation events in this configuration.

![idea_tabs_settings](https://cloud.githubusercontent.com/assets/959228/11281832/0c8a92d0-8ec2-11e5-99b2-4573e71cd19f.png)

**Comment by nicity** [comment]
IMO these GlancePanel should be cached with SoftReference anyway, many of these panels are about 8M

**Comment by Vektah** [comment]
@talanb Its pretty annoying that fileClosed isn't called with the tab bar turned off. I'm now scanning for unused panels on fileOpen now also.

Also added soft references to play nicer with the GC.
